name: smoketest

on:
  workflow_dispatch:

env:
  ARCH: arm64
  REGISTRY: ghcr.io
  IMAGE_NAME: vyos-current-arm64

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    # runs-on: ubuntu-24.04
    permissions:
      contents: write
    container:
      image: ghcr.io/sever-sever/vyos-build-arm64:latest
      options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          path: vyos-build-arm64
         
      - name: Checkout vyos-build repo
        uses: actions/checkout@v6
        with:
          repository: vyos/vyos-build
          ref: current
          path: vyos-build
          # repository: c-po/vyos-build
          # ref: kernel-serial-activation
          # path: vyos-build

      # Check grub fix for AMA
      # - name: Checkout vyos-1x repo
      #   working-directory: vyos-build/scripts/package-build/vyos-1x
      #   run: |
      #     git clone -b current --single-branch https://github.com/vyos/vyos-1x.git
      #     cd vyos-1x
      #     dpkg-buildpackage -us -uc -b
      #     cp ../*.deb ../../../../packages/

      # - name: Check vyos-1x binaries
      #   working-directory: vyos-build
      #   run: |
      #     ls -lah packages
          
      # - name: Copy flavors to vyos-build
      #   run: |
      #     rsync -avh vyos-build-arm64/data/build-flavors/ vyos-build/data/build-flavors/

      - name: Build VyOS image
        working-directory: vyos-build
        run: |
          # ./build-vyos-image --architecture arm64 generic-arm64
          ./build-vyos-image --architecture arm64 generic

      - name: Check .iso file
        working-directory: vyos-build
        run: |
          ls -lah build

      - name: Run smoketests
        working-directory: vyos-build
        run: |
          arch="arm64"
          # sudo make test-no-interfaces-no-vpp | tee tmp.log
          scripts/check-qemu-install --debug --configd --smoketest --uefi --no-interfaces --no-vpp --cpu-type cortex-a53 --memory 2 --iso build/live-image-${arch}.hybrid.iso
